### ISSUE TITLE
昨天开始突然崩了

### ISSUE THREAD

**Issue by wanghaisheng** [QIN2DIM/V2RayCloudSpider#30]
最新版本始终提示升级，使用4.5.1 得到如下error
```
HTTPSConnectionPool(host='t.qinse.top', port=443): Max retries exceeded with url: /subscribe/version_manager.txt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))


Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='t.qinse.top', port=443): Max retries exceeded with url: /subscribe/version_manager.txt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MiddleKey\version_IO.py", line 105, in run
  File "MiddleKey\version_IO.py", line 181, in get_server_version
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='t.qinse.top', port=443): Max retries exceeded with url: /subscribe/version_manager.txt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))


```

**Comment by QIN2DIM** [comment]
采集器指令堆积，内存溢出，小bug，已修复=。=
